### ISSUE TITLE
try to got data from huobi fail

### ISSUE THREAD

**Issue by xtuyaowu** [crypto-crawler/crypto-crawler-rs#24]
below is detail logs thanks !

    // crawl_trade("huobi", MarketType::Spot, symbols_opt, tx).await;
    // crawl_l2_event("huobi", MarketType::Spot, symbols_opt, tx).await;
    // crawl_l2_topk("huobi", MarketType::Spot, None, tx).await;
    //crawl_bbo("huobi", MarketType::Spot, None, tx).await;
    // crawl_candlestick("huobi", MarketType::Spot, None, tx).await;
    // crawl_funding_rate("huobi", MarketType::Spot, None, tx).await;

thread 'main' panicked at 'Failed to connect to websocket: Io(Os { code: 60, kind: TimedOut, message: "Operation timed out" })', /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-ws-client-4.11.4/src/common/ws_client_internal.rs:50:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: crypto_ws_client::common::ws_client_internal::WSClientInternal<H>::connect::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-ws-client-4.11.4/src/common/ws_client_internal.rs:48:40
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: crypto_ws_client::clients::huobi::HuobiWSClient<_>::new::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-ws-client-4.11.4/src/clients/huobi.rs:98:14
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   8: crypto_crawler::crawlers::huobi::crawl_l2_event::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-crawler-4.4.0/src/crawlers/huobi.rs:34:89
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  10: crypto_crawler::crawl_l2_event::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/crypto-crawler-4.4.0/src/lib.rs:260:77
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  12: test::main::{{closure}}
             at ./crypto-test/src/test.rs:95:63
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  15: tokio::coop::with_budget::{{closure}}
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  18: tokio::coop::with_budget
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  19: tokio::coop::budget
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  20: tokio::park::thread::CachedParkThread::block_on
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  21: tokio::runtime::enter::Enter::block_on
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  22: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/mod.rs:90:9
  23: tokio::runtime::Runtime::block_on
             at /Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/mod.rs:482:43
  24: test::main
             at ./crypto-test/src/test.rs:95:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by soulmachine** [comment]
I think Huobi is  probably blocked in your country, are you able to access www.huobi.com in browser?
